# Generated by Django 3.2.25 on 2024-10-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_rename_email_contact_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email_address',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
